version: "3.9"

services:
  app:
    build: .
    container_name: ssti-challenge
    ports:
      - "3010:3000"
    environment:
      - FLAG=shellmates{s7i_byp4ss_v1a_c0nt3xt_p0llut10n}
    restart: unless-stopped
